name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs:
  pipeline:
    uses: itsbigspark/the-one-continuous-integration/.github/workflows/mcp-server-pipeline.yml@main
    with:
      image-name: ${{ github.event.repository.name }}
